### ISSUE TITLE
Multiple screen shots are not attached

### ISSUE THREAD

**Issue by JameyRandall** [Magenic/MAQS#10]
Issue 1: when a soft assert fails part way through a test a screen shot is still taken of the last page even though the assert on the last page passed.

Issue 2:  when a test has multiple soft asserts and more than one of them fail, the screen shots for each failure are not attached. 
                Looking through the log file and in the log folder I can see that multiple screen shots were taken.

Maqs Version: 5.1.1

Execution: local or grid

Here are the two scenarios I used for testing:
Scenario 1 – One failure in scenario
Steps:
1.	Launch application
2.	Navigate to new page
3.	Soft assert fail
4.	Navigate to new page
5.	Soft assert pass
6.	Navigate to new page
7.	End Test
Expected: Screen shot from step 3
Actual: screen shot taken on Step 6 and attached
 
Scenario 2 – Multiple failures in scenario
Steps:
1.	Launch application
2.	Navigate to new page
3.	Soft assert pass
4.	Navigate to new page
5.	Soft assert fail
6.	Navigate to new page
7.	Soft assert pass
8.	Navigate to new page
9.	Soft assert fail
10.	Navigate to new page
11.	Soft assert pass
12.	Navigate to new page
13.	End Test
 
Expected: Screen shots from steps 5 & 9 attached, no screen shot for step 12
Actual: screen shot taken from Step 12 and attached

**Comment by TroyWalshProf** [comment]
We are looking at ways of adding these attachments is a sensible manner.

**Comment by TroyWalshProf** [comment]
A fix being worked on right now and should be out early next week.

**Comment by TroyWalshProf** [comment]
The fix is being tested right now, should have an official release in the next couple of days
