### ISSUE TITLE
Maqs isn't installed at the VS 2019

### ISSUE THREAD

**Issue by pulversss** [Magenic/MAQS#12]
Hi Guys! 

Microsoft Visual Studio Enterprise 2019
4/3/2019 10:53:15 AM - 		-------------------------------------------------------
4/3/2019 10:53:15 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
4/3/2019 10:53:15 AM - 		Name         : Visual Studio core editor
4/3/2019 10:53:15 AM - 		Version      : [15.0,16.0)
4/3/2019 10:53:15 AM - 		Error        : The prerequisite version specified does not match the version installed
4/3/2019 10:53:15 AM - 
4/3/2019 10:53:15 AM - 		-------------------------------------------------------
4/3/2019 10:53:15 AM - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
4/3/2019 10:53:15 AM - 		Name         : C# and Visual Basic
4/3/2019 10:53:15 AM - 		Version      : [15.0.26208.0,16.0)
4/3/2019 10:53:15 AM - 		Error        : The prerequisite version specified does not match the version installed
4/3/2019 10:53:15 AM - 
4/3/2019 10:53:15 AM - 		-------------------------------------------------------
4/3/2019 10:53:15 AM - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
4/3/2019 10:53:15 AM - 		Name         : .NET desktop development tools
4/3/2019 10:53:15 AM - 		Version      : [15.0.26208.0,16.0)
4/3/2019 10:53:15 AM - 		Error        : The prerequisite version specified does not match the version installed
4/3/2019 10:53:15 AM - 
4/3/2019 10:53:15 AM - 		-------------------------------------------------------
4/3/2019 10:53:15 AM - 		Identifier   : Microsoft.Net.Component.4.7.1.SDK
4/3/2019 10:53:15 AM - 		Name         : .NET Framework 4.7.1 SDK
4/3/2019 10:53:15 AM - 		Version      : [15.6.27406.0,16.0)
4/3/2019 10:53:15 AM - 		Error        : The prerequisite version specified does not match the version installed

But many of the components are installed.

**Comment by TroyWalshProf** [comment]
The top end version of those components don't work with VS 2019. 
They have top ends like 16.0.234.
An update is being pushed to the Marketplace right now.

**Comment by pulversss** [comment]
Thanks, Guys! 

Done!
