### ISSUE TITLE
Timeout configuration in 5.4

### ISSUE THREAD

**Issue by ParanoikCZE** [Magenic/MAQS#13]
After upgrading from 4.0.5 to 5.4.0 we experience issues with waits.
E.g. this code doesn't wait for anything
testObject.WebDriver.Wait().ForPageLoad();
If I wait for page load with static thread sleep, I am able to fill and check forms, however, when I wait for anything, the test ends with "Message: System.TimeoutException : Page load took longer than timeout configuration".

The same code worked in the older version. I've extended timeouts in app.config, but that doesn't seem to affect anything as this fail is almost instant. Any ideas what's wrong here?

```
<configSections>
    <section name="MagenicMaqs" type="System.Configuration.NameValueSectionHandler" />
  </configSections>
  <MagenicMaqs>
    <add key="Browser" value="Chrome" />
    <add key="WaitTime" value="1000" />
    <add key="Timeout" value="30000" />
    <add key="Log" value="OnFail" />
    <add key="LogLevel" value="INFORMATION" />
    <add key="LogType" value="TXT" />
    <add key="ImageFormat" value="Png" />
  </MagenicMaqs>
```

**Comment by TroyWalshProf** [comment]
We revamped how we handle our config files. 
See: https://magenic.github.io/MAQS/#/MAQS_5/SeleniumConfig
The basic idea is that we wanted to stop throwing everything into one section.

**Comment by billros** [comment]
It appears your app.config is still in the 4.0.5 format.

The app.config has been reorganized in 5.x to better group settings by their effect (general framework vs Selenium).

So, the wait settings would be in the new SeleniumMaqs session.






On Apr 3, 2019 7:29 AM, ParanoikCZE <notifications@github.com> wrote:

After upgrading from 4.0.5 to 5.4.0 we experience issues with waits.
E.g. this code doesn't wait for anything
testObject.WebDriver.Wait().ForPageLoad();
If I wait for page load with static thread sleep, I am able to fill and check forms, however, when I wait for anything, the test ends with "Message: System.TimeoutException : Page load took longer than timeout configuration".

The same code worked in the older version. I've extended timeouts in app.config, but that doesn't seem to affect anything as this fail is almost instant. Any ideas what's wrong here?

<configSections>
    <section name="MagenicMaqs" type="System.Configuration.NameValueSectionHandler" />
  </configSections>
  <MagenicMaqs>
    <add key="Browser" value="Chrome" />
    <add key="WaitTime" value="1000" />
    <add key="Timeout" value="30000" />
    <add key="Log" value="OnFail" />
    <add key="LogLevel" value="INFORMATION" />
    <add key="LogType" value="TXT" />
    <add key="ImageFormat" value="Png" />
  </MagenicMaqs>

**Comment by TroyWalshProf** [comment]
This may also be userful:
https://github.com/Magenic/MAQS/issues/5

**Comment by ParanoikCZE** [comment]
Thank you guys, I'm not sure how I miss this while looking through docs. However, it still didn't help. Even if I use app.config example from https://magenic.github.io/MAQS/#/MAQS_5/SeleniumConfig without single change, code then returns:
SeleniumConfig.GetCommandTimeout(); //60
SeleniumConfig.GetTimeoutTime(); //0
SeleniumConfig.GetWaitTime(); //0

**Comment by matt-helgerson** [comment]
for #1. There are a few things you could do. Now the driver is lazy loaded. the two easiest options are to:
1.) Override the GetBrowser() function
`
protected override IWebDriver GetBrowser()
        {
            var newOptions = WebDriverFactory.GetDefaultChromeOptions();
            newOptions.AddArguments("--no-sandbox");

            return WebDriverFactory.GetChromeDriver(TimeSpan.FromSeconds(2), newOptions, "MAXIMIZE");
        }
`

2.) Just re-assign the WebDriver
`
var newOptions = WebDriverFactory.GetDefaultChromeOptions();
            newOptions.AddArguments("--no-sandbox");

            this.WebDriver = new ChromeDriver(newOptions);
`
For #2, Maybe I am misunderstanding your question/statement, but the app.config is only used for the selenium config, which should not really need to be updated or changed between different services/applications too much.

For #3, you are correct it looks like the fall-back values are 0, but that only happens if the config value is not found in the app.config at all, which is where it gets the timeouts values. The default app.config values are 60 seconds, 1 second, and 10 seconds respectively.

**Comment by TroyWalshProf** [comment]
I am guessing the config issues you are still have is because you missed of skipped a step.
[#5](https://github.com/Magenic/MAQS/issues/5) - Step 8
*This is why I  am a big fan of the "easy" instructions.

As far as the "--no-sandbox" thing goes ...
The issue is that when your tests as a service Chrome automatically runs in headless mode.  In pervious versions Chrome automatically set this flag itself, but that latest release stopped doing that.
The easy and arguably correct answer is use the "HeadlessChrome" browser option as this one sets "--no-sandbox".
That being said it you want total control Matt's solution is spot on.

**Comment by ParanoikCZE** [comment]
@matt-helgerson #2 it doesn't mean only MAQS. In common, there could be dozens of projects in same folder. What if every single one of them would load config from app.config instead of projectName*.config?

**Comment by ParanoikCZE** [comment]
@matt-helgerson #1 big thanks .. I wasn't aware of a possibility to override driver construction, so this makes it work for me.

**Comment by TroyWalshProf** [comment]
@ParanoikCZE - Are you still experiencing issues?
Note* There was an update to chrome that appears to have addressed the sandbox issue.

I am fairly curtain the sandbox issue was a Chrome issue.  Headless mode requires no-sandbox.  The Chromium team changing thing up 2-3 years ago to automatically set no-sandbox when the browser was being used headless.

**Comment by ParanoikCZE** [comment]
I'm pretty sure this is more related to OS version than Chrome itself, as that was only single thing which changed before our framework stopped to work.
But maybe Chrome has issues with detecting OS properly as first topics about this issue to find are exactly 2-3 years old.

So, for me, issue was resolved with overriding GetBrowser (at least I hope, our full execution round should finish in few hours from now) but I'm still curious about that app.config static file name. Can that be fixed somehow?

**Comment by ParanoikCZE** [comment]
I'm not working with .Net standard, so I have no clue .. I'm getting that now.

Btw would be nice to have some email conference, google group or something for support topics like this one to avoid creating issues which are actually "by design".

Which takes me to another question. How to safely and effectively kill WebDriver/Browser? As if I do something like WebDriver?.Quit(), it will create a new instance first if it was properly closed previously. Seems like our agent is now fighting with some reporting and in some cases (still investigating) WebDriver and Chrome remains running. Well, you can probably imagine how a server with a few thousands of these is fast.

**Comment by TroyWalshProf** [comment]
Thanks for the feedback.
Letting the community know what is coming down the line is a great idea, that should have been happening for a long time. - Strongly considering adding GitHub projects.

Here is how we safely cleanup drivers:
https://magenic.github.io/MAQS/#/MAQS_5/SeleniumUtils?id=killdriver

As to the orphaned browser issue, we had the same issue on our build server.  
This was related to the headless Chrome issue.  When Chrome stopped automatically running headless Chrome with no-sandbox our test runs started orphaning browser instances. We had to bounce our build server and add the no-sandbox fix before we could get our build server back to a good state.

**Comment by TroyWalshProf** [comment]
@ParanoikCZE  is this still an issue?

**Comment by ParanoikCZE** [comment]
@TroyWalshProf I think we can close this. Thanks for your support guys.
