### ISSUE TITLE
Update Description and tags for MAQS 6.0 NuGet packages

### ISSUE THREAD

**Issue by FermJacob** [Magenic/MAQS#189]
@billros We need updated descriptions and tags for the individual projects 

&lt;Description&gt;Magenic's automation quick start framework&lt;/Description>
&lt;PackageTags&gt;test selenium appium automation NUnit MSTest TestFramework&lt;/PackageTags&gt;

The projects we need these updates for are:
BaseAppiumTest
BaseDatabaseTest
BaseEmailTest
BaseMongoTest
BaseCompositeTest
BaseWebServiceTest

**Comment by billros** [comment]
Here is suggested wording of the NuGet descriptions and tags.  Please add any technology specific keywords to the Tags lists!

BaseAppiumTest
<Description>Appium extension for Magenic's automation quick start framework</Description>
<PackageTags>test selenium appium automation NUnit MSTest TestFramework</PackageTags>

BaseDatabaseTest
<Description>Database extension for Magenic's automation quick start framework</Description>
<PackageTags>test SQL database automation NUnit MSTest TestFramework</PackageTags>

BaseEmailTest
<Description>Email extension for Magenic's automation quick start framework</Description>
<PackageTags>test email automation NUnit MSTest TestFramework</PackageTags>

BaseMongoTest
<Description>Mongo extension for Magenic's automation quick start framework</Description>
<PackageTags>test mongo database automation NUnit MSTest TestFramework</PackageTags>

BaseCompositeTest
<Description>Composite extension for Magenic's automation quick start framework.  Includes all MAQS extensions.</Description>
<PackageTags>test selenium appium automation NUnit MSTest TestFramework</PackageTags>


BaseWebServiceTest
<Description>Web Service extension for Magenic's automation quick start framework</Description>
<PackageTags>test Web service http client automation NUnit MSTest TestFramework</PackageTags>
