### ISSUE TITLE
Appium Script not running due to " webDriver.Manage().Window.Maximize();" line

### ISSUE THREAD

**Issue by SnigdhaSuchismitaDash** [Magenic/MAQS#2]
We are trying to integrate appium with MAQS framework.  The following error was found after executing a simple script.
unknown error: operation is unsupported on Android
  (Session info: chrome=60.0.3112.107)
  (Driver info: chromedriver=2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a),platform=Windows NT 6.3.9600 x86_64).

This problem is appearing due to a code bug in BaseTest--> SeleniumConfig.cs-->Browser function. The code is highlighted in the attached screenshot. Maximize window command don't work in appium.
![capture](https://user-images.githubusercontent.com/10626268/30004580-d6b59ee8-90ef-11e7-8514-aa34cbc4def4.PNG)

**Comment by TroyWalshProf** [comment]
First off, thanks for providing such good background.  Makes addressing bugs soooo much easier.

So I have a couple of answers for you.
1. We knew these basic configurations would not work for every single project.  That is whey we allow you to override the BaseSeleniumTest GetBrowser call.
Example:
```
        /// <summary>
        /// Override the web driver we user for these tests
        /// </summary>
        /// <returns>The web driver we want to use - Web driver override</returns>
        protected override IWebDriver GetBrowser()
        {
            ChromeOptions chromeOptions = new ChromeOptions();
            chromeOptions.AddArgument("test-type");
            chromeOptions.AddArguments("--disable-web-security");
            chromeOptions.AddArguments("--allow-running-insecure-content");
            chromeOptions.AddArguments("--disable-extensions");
            return  new ChromeDriver(GetDriverLocation("chromedriver.exe"), chromeOptions);
        }
```

2.  The product owner and I have been talking about making maximization and screen resolution configurable - This bug may bump that enhancement up the stack

3. The enterprise version of MAQS includes a Appium module that we are working on getting open sourced.

**Comment by SnigdhaSuchismitaDash** [comment]
Thanks for your quick reply. By Overriding GetBrowser Function,  I am able to execute appium script.

I have some doubts regarding this framework.

1. When will the enterprise version of MAQS Framework which include Appium Module will be open sourced?
2. Does MAQS framework support iOS platform(i.e. Safari)? What other platform it support?
3. How to access functionality of Find.cs class? Find.cs will be found at BaseSeleniumTest-->Extension-->Find.cs


Kindly provide your contact details for further consulting

**Comment by TroyWalshProf** [comment]
1. No ETA on open sourcing Appium module - Management is still discussing if/when other modules go open source

2. MAQS supports Safari and other platforms via grid: https://github.com/Magenic/MAQS/wiki/Configuration#remote-browser-settings
http://bugsareinthegaps.com/an-intro-to-selenium-grid/

3.  To use the extension classes you need to add the namespace:
`using Magenic.MaqsFramework.BaseSeleniumTest.Extensions;`

**Comment by SnigdhaSuchismitaDash** [comment]
Thank you very much for your valuable information.

**Comment by TroyWalshProf** [comment]
Next release we are adding a config setting that will let you  define your browser resolution.  This will also let you just use the default an not try to resize the browser, which should fix your issue.
See: https://github.com/Magenic/MAQS/blob/develop/Framework/BaseSeleniumTest/SeleniumConfig.cs
