### ISSUE TITLE
Screenshot and Log does not attach - .Net Core 2.0

### ISSUE THREAD

**Issue by JameyRandall** [Magenic/MAQS#22]
I have setup a simple project to work though moving our test automation to .Net Core 2.X and I am finding that the log file and screen shots are not showing up in the output for a failed test. 

Version: 5.5.0
TargetFramework: Netcoreapp2.0
Selenium: 3.141
Chrome Driver: 76.0.3 (latest)
IE: 3.141.59
Environment: Local machine, no gird

Test:
  public void VerifyAppLoads()
        {
            HomePageModel homePage = new HomePageModel(TestObject, true);
            homePage.WaitForPageLoad();

            this.SoftAssert.IsFalse(true, "Force Fail");
            this.SoftAssert.FailTestIfAssertFailed();
        }

Appsettings.json:
{
  "MagenicMaqs": {
    "WaitTime": "100",
    "Timeout": "10000",
    "Log": "OnFail",
    "LogLevel": "VERBOSE",
    "LogType": "TXT",

  },
  "SeleniumMaqs": {
    "WebSiteBase": "https://siteurl.com/",
    "Browser": "Chrome",
    "HubUrl": "http://ourhubmachine:4444/wd/hub",
    "RemoteBrowser": "Chrome",
    "SeleniumCommandTimeout": "60000",
    "BrowserWaitTime": "100",
    "BrowserTimeout": "10000",
    "BrowserSize": "MAXIMIZE",
    "SoftAssertScreenshot": "Yes",
    "ImageFormat": "Png",
    "SavePagesourceOnFail": "NO"
  },
  "RemoteSeleniumCapsMaqs": {
    "Username": "Sauce_Labs_Username",
    "AccessKey": "Sauce_Labs_Accesskey",
    "BrowserName": "Chrome",
    "Platform": "OS X 10.11",
    "Version": "54.0"
  }
}

**Comment by TroyWalshProf** [comment]
This is a limitation of MSTest.
If I am not mistaken this enhancement should be become available once MSTest 2.0 get's released.
https://github.com/microsoft/testfx/pull/609

Once MS releases this enhancement we will likely need to update the MAQS code, but for right now we have to wait on MS.

**Comment by JameyRandall** [comment]
reverted to 4.7.1 for now, thanks.

**Comment by JameyRandall** [comment]
MS Test 2.0 came out this morning and it was indicated that #609 was in this release.  I tried a few tests on my side using netcoreapp2.0 with today's release of MSTest on Maqs 5.5.1 and the files are still not attaching. 

Could you confim if MS Test 2.0 fixed the attachment issue on your end? 

https://github.com/microsoft/testfx/releases/tag/v2.0.0

**Comment by FermJacob** [comment]
There will need to be a code change in MAQS to have utilize this new functionality

[Code Reference](https://github.com/Magenic/MAQS/blob/d5dfbb30d2815293ff9cad6498f14ec156bb9476/Framework/BaseTest/BaseTest.cs#L577)

We will put this on the TODO and validate the fix

**Comment by FermJacob** [comment]
@JameyRandall This should be fixed in the latest version of MAQS

5.5.2 - 2019/9/5
     Bug fixes and minor enhancements
     - Add associated files to Core MSTest test results
     Package update
     - Add Mongo module to the package
     Template updates
     - Mass dependency updates

**Comment by JameyRandall** [comment]
Updated to 5.5.2 and set targeting framework to 2.2.   The log files and screen shots are now getting attached. 

Thanks!
