### ISSUE TITLE
LazyElement issue when calling FindElements

### ISSUE THREAD

**Issue by FermJacob** [Magenic/MAQS#285]
After upgrading to MAQS 5.8, some of our LazyElement implementations have been failing with the error:

 System.ArgumentException: The IWebElement object must implement or wrap an element that implements ILocatable.
    Parameter name: element

I was able to reproduce with the a new Selenium template with the following code change to the LoginPageModel

```
        private LazyElement Body
        {
            get { return this.GetLazyElement(By.CssSelector("body"), "body"); }
        }

        public HomePageModel LoginWithValidCredentials(string userName, string password)
        {

            //This works
            var elements = this.WebDriver.FindElement(By.CssSelector("body")).FindElements(By.CssSelector("input"));
            Actions a = new Actions(this.WebDriver);
            a.MoveToElement(elements[0]).Build().Perform();

            // This does not work
            var elements1 = this.Body.FindElements(By.CssSelector("input"));
            Actions a1 = new Actions(this.WebDriver);
            a1.MoveToElement(elements1[0]).Build().Perform();


            this.EnterCredentials(userName, password);
            this.LoginButton.Click();

            return new HomePageModel(this.TestObject);
        }
```

**Comment by TroyWalshProf** [comment]
I have a cheesy workaround:

Change
a1.MoveToElement(elements1[0]).Build().Perform();
to
a1.MoveToElement(((LazyElement)elements[0]).CachedElement).Build().Perform();

**Comment by TroyWalshProf** [comment]
This  will be officially "fixed" in the MAQS 6 release 
See #312 and https://github.com/Magenic/MAQS/commit/4809094db83ea6c5756e0e772291e299d5dafcaa
for the MAQS 6 changes

For V5 we are just reverting back to returning raw IWebElements on finds.
See: https://github.com/Magenic/MAQS/blob/edc42db5615bad071cc1fc8c15e8a726db07ce95/Framework/BaseSeleniumTest/Extensions/AbstractLazyIWebElement.cs#L617
