### ISSUE TITLE
MAQS 5.8 Issue - Lazy Element cannot convert to IWrapsDriver

### ISSUE THREAD

**Issue by jhorne12345** [Magenic/MAQS#287]
When trying to wait for a nested element to be clickable I receive the following error. Please see the attached zip for further details

`System.InvalidCastException: 'Unable to cast object of type 'Magenic.Maqs.BaseSeleniumTest.Extensions.LazyElement' to type 'OpenQA.Selenium.Internal.IWrapsDriver'.'`

**Code Snippet:**
```
            var table = this.GetLazyElement(By.TagName("table"));

            var row = table.FindElement(By.TagName("tr"));
            
            var icon = this.GetLazyElement(By.XPath("//a[text() = 'Edit']"), "Edit Icon");
			
            ///This doesn't work below.
            row.Wait().ForClickableElement(icon.By);
```

[SeleniumBugFramework.zip](https://github.com/Magenic/MAQS/files/4258470/SeleniumBugFramework.zip)

**Comment by JeffreyZacher** [comment]
@FermJacob Do you think this has anything to do with #285

**Comment by TroyWalshProf** [comment]
Lazy elements have their own built in waiting, also we implemented parent lazy elements for this exact purpose.

Example: 
``` csharp
var table = new LazyElement(TestObject, By.TagName("table"));
var row = new LazyElement(table, By.TagName("tr"));
var icon = new LazyElement(row, By.XPath("//a[text() = 'Edit']"));
```

**Comment by TroyWalshProf** [comment]
This  will be officially "fixed" in the MAQS 6 release 
See #312 and https://github.com/Magenic/MAQS/commit/4809094db83ea6c5756e0e772291e299d5dafcaa
for the MAQS 6 changes

For V5 we are just reverting back to returning raw IWebElements on finds.
See: https://github.com/Magenic/MAQS/blob/edc42db5615bad071cc1fc8c15e8a726db07ce95/Framework/BaseSeleniumTest/Extensions/AbstractLazyIWebElement.cs#L617
