### ISSUE TITLE
MAQS 5.8 - BaseDatabaseTest

### ISSUE THREAD

**Issue by JameyRandall** [Magenic/MAQS#288]
namespace Magenic.Maqs.BaseDatabaseTest

The overloads for DatabaseDriver were removed in MAQS 5.8.  We pass in the data provider and connection string when creating the connection. 

was    public DatabaseDriver(string providerType, string connectionString);  removed for a reason? 

This will prevent us from preventing us from upgrading form 5.7 to 5.8.

**Comment by FermJacob** [comment]
Hi @JameyRandall,

I am not seeing a change in the overloads for a DatabaseDriver.  The providerType and connectionString still exist
https://github.com/Magenic/MAQS/blob/93a4cd195c9818e4bef9813ed525f4df995b7557/Framework/BaseDatabaseTest/DatabaseDriver.cs#L33

Can you provide some sample code for us to reproduce?  What is the scenario you are trying to perform?  Would using the ManagerStore be better?

``` csharp
this.ManagerStore.Add("CustomKey", new DatabaseDriverManager(() => DatabaseConfig.GetOpenConnection("SQLSERVER", "DBConnectionString"),this.TestObject));
```

**Comment by JameyRandall** [comment]
public static DatabaseDriver DBConnect(string sqlUser, string server, string database, bool security = false)
        {
            string sqlPassword = Login.GetPassword(sqlUser);
            string connectString = BuildConnectionString(sqlUser, sqlPassword, server, database, security);
            return new DatabaseDriver("SQLSERVER", connectString);
        }


 Message: 
    Test method UnitTests.SQL.DatabaseTests.ValidateFirstRow threw exception: 
    System.TypeInitializationException: The type initializer for 'Magenic.Maqs.BaseDatabaseTest.DatabaseConfig' threw an exception. ---> Magenic.Maqs.Utilities.Helper.MaqsConfigException: Key missing DataBaseConnectionString
    Key missing DataBaseProviderType

**Comment by JameyRandall** [comment]
![image](https://user-images.githubusercontent.com/46896613/75553565-44429180-59fe-11ea-8139-1364c1f80000.png)

**Comment by TroyWalshProf** [comment]
@FermJacob - The error Jamey provided is a config validation error.
It's related to what Bill in recommending in #286 

@JameyRandall, you just need to add the missing config keys:
https://magenic.github.io/MAQS/#/MAQS_5/Database/DatabaseConfig
*You need the DataBaseProviderType and DataBaseConnectionString keys

**Comment by TroyWalshProf** [comment]
Fwiw - It is working as designed :)

**Comment by FermJacob** [comment]
@JameyRandall,

To add to @TroyWalshProf's comment, you will need to add these values into the config and it will pass the config validation.

``` json
"DatabaseMaqs": {
    "DataBaseProviderType": "",
    "DataBaseConnectionString": ""
  }, 
```

**Comment by JameyRandall** [comment]
Confirmed adding the DatabaseMaqs keys fixes the issue.
