### ISSUE TITLE
Appium throwing System.NotImplementedException: Not implemented yet for script.. error for native apps

### ISSUE THREAD

**Issue by TroyWalshProf** [Magenic/MAQS#290]
When you run a native app Android or iOS app you get the following error:
System.NotImplementedException: Not implemented yet for script..

This because we set the AsynchronousJavaScript and PageLoad timeouts, which makes no sense at all.

**Comment by FermJacob** [comment]
#311 

@TroyWalshProf Can you confirm the fix has been merged?

**Comment by TroyWalshProf** [comment]
Confirmed
