### ISSUE TITLE
Implement LazyElement changes

### ISSUE THREAD

**Issue by FermJacob** [Magenic/MAQS#312]
Add the two following methods:
FindRawElement()
FindRawElements()

These will return a IWebElement, which is type of RemoteWebElement

Refactor the existing code for FindLazyElement(s) to the following methods:
FindElement()
FindElements()
These will return a LazyElement

Add in documentation on the changes this bring to LazyElements
- Update method names and examples
- Include documentation on how to upgrade existing FindElement and FindElements to FindRaw...

Investigate and update Unit tests

Re-name the following methods 
GetTheVisibleElement
GetTheClickableElement
GetTheExistingElement
GetIndexed

Convert the names of the method to use "GetRaw..."

**Comment by TroyWalshProf** [comment]
@FermJacob - Mind taking a look to confirm that https://github.com/Magenic/MAQS/commit/4809094db83ea6c5756e0e772291e299d5dafcaa 
Addresses this issue?

**Comment by FermJacob** [comment]
@TroyWalshProf We are missing documentation on the upgrade path from 5.8.1 to 6.0 with the re-write of FindElements to FindRawElements.  We should also add some FAQs to LazyElement for the #287 & #285 issues
