### ISSUE TITLE
Duplicate screen shots 

### ISSUE THREAD

**Issue by JameyRandall** [Magenic/MAQS#33]
MAQS 5.5.2
.NetCore 2.2

When a test fails due to a soft assert, two screen shots are captured and both are attached to the test.  What I am seeing is the log is that a screen shot is taken at the time of the soft assert failure again at SoftAssert.FailTestIfAssertFailed();

[Module1.Selenium.SeleniumTest.MSOAVerifyAppLoads - 2019-09-09-07-35-21-5577.txt](https://github.com/Magenic/MAQS/files/3592250/Module1.Selenium.SeleniumTest.MSOAVerifyAppLoads.-.2019-09-09-07-35-21-5577.txt)

**Comment by FermJacob** [comment]
Hi @JameyRandall 

If you fail another soft assertion, do you get 3 images?

**Comment by JameyRandall** [comment]
Yes there is always 1 more screen shot than the number of soft asserts. Is this how it is supposed to work? Is the idea to capture the state of the application when it closes or should it only take screen shots at when the soft assert fails?

**Comment by billros** [comment]
Yes.  If we are logging to a file and the test is not PASSing,  we capture a final screenshot.
Since it is a visual test (selenium), and we don’t know how far you have navigated after the last Soft Assert, we err on the side of a (potentially duplicate) final state screen-shot.

**Comment by JameyRandall** [comment]
That makes sense and I agree it is good to know the final state of the UI when a test fails.  

Could we turn this into an enhancement request to name the screen shots in a way that reflects the order in which they were taken an maybe the final state screen shot contains final or something in the file name?

**Comment by FermJacob** [comment]
@JameyRandall Yes we can add a clearer message to the final screenshot

@billros @TroyWalshProf  I purpose a " - Final" to the end screenshot.  Thoughts?

**Comment by FermJacob** [comment]
@JameyRandall This will be included in the MAQS 5.6 deployment
