### ISSUE TITLE
Cannot load dependency

### ISSUE THREAD

**Issue by ParanoikCZE** [Magenic/MAQS#366]
After upgrade 5.8.1 => 5.8.2, cannot execute anything, with:
```
  Message: 
    System.TypeInitializationException : The type initializer for 'Magenic.Maqs.Utilities.Helper.Config' threw an exception.
      ----> System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Extensions.Configuration.Json, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Systém nemůže nalézt uvedený soubor.
    TearDown : System.TypeInitializationException : The type initializer for 'Magenic.Maqs.Utilities.Helper.Config' threw an exception.
      ----> System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Extensions.Configuration.Json, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Systém nemůže nalézt uvedený soubor.
  Stack Trace: 
    Config.GetGeneralValue(String key, String defaultValue)
    LoggingConfig.GetLoggingEnabledSetting()
    BaseTest.CreateLogger()
    BaseSeleniumTest.CreateNewTestObject()
    BaseTest.Setup()
    --FileNotFoundException
    Config.cctor()
    --TearDown
    Config.GetGeneralValue(String key, String defaultValue)
    LoggingConfig.GetLoggingEnabledSetting()
    BaseTest.CreateLogger()
    BaseSeleniumTest.CreateNewTestObject()
    BaseTest.get_TestObject()
    BaseTest.get_SoftAssert()
    BaseTest.Teardown()
    --FileNotFoundException
    Config.cctor()
```

NuGet is downloaded but not copied to output directory.

**Comment by TroyWalshProf** [comment]
@ParanoikCZE - Which version of .net is your code targeting?

**Comment by ParanoikCZE** [comment]
3.1

**Comment by FermJacob** [comment]
@TroyWalshProf I created a new composite project against 3.1 for both NUnit and MSTest.  I am unable to reproduce the issue.  

@ParanoikCZE Can you validate a few items for me:
1. Do you have a package reference to     
`<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.1" />`?
2. Could you try updating to 3.1.4?
3. Does the dll exist in the output folder?  ex. \bin\Debug\netcoreapp3.1\Microsoft.Extensions.Configuration.Json.dll
4. Are you using MSTest or NUnit?
5. Is this exception being thrown inside a Test or a test/class initialize?

**Comment by ParanoikCZE** [comment]
While playing with a bit, found out that removing obj folders do the job.

**Comment by TroyWalshProf** [comment]
That is weird, thanks for letting us know how you got around the issue.
