### ISSUE TITLE
Support for VS 2019 for Mac

### ISSUE THREAD

**Issue by pjotal** [Magenic/MAQS#383]
Tried to install your package from the market place and from file and none of them worked so I guess there is no support for VS 2019 for Mac. Therefore this ticket is so you can think and package at least the framework portion for mac.

**Comment by pjotal** [comment]
That's good news. Is (3) described in more details somewhere in the documentation?
For (4), does the documentation list which version of chrome is supported?

thanks.

**Comment by TroyWalshProf** [comment]
The [docs](https://magenic.github.io/MAQS/#/MAQS_6/Introduction) will be updated with this info. - Hopefully before MAQS 6 is released.

So which version of Chrome is supported is kind of complicated.  
MAQS itself can work with almost any version of Chrome, the trick is that you will need a compatible version of the web driver.
We pull in the Chrome (and other browsers) driver via NuGet.  
See: https://github.com/Magenic/MAQS-Extensions/blob/master/Extensions/CoreTemplates/Magenic.Maqs.Selenium.Template/Tests/Tests.csproj#L12
Over time Chrome (and the other browsers) will make changes which are incompatible with older versions of their web drivers.  When that happens you just need to update your Chrome driver package and you are back up and running.

**Comment by FermJacob** [comment]
For 3, here is the PR that removed the PostBuildEvents from the extensions.
https://github.com/Magenic/MAQS-Extensions/pull/38

**Comment by billros** [comment]
As you can see from the responses from Jake and Troy, it is possible to use the MAQS framework with VS 2019 for MAC.  Given the low number of users/requests for MAC "out-of-the-box" templates, this is very low on our list of things to work on.

**That said: MAQS is an open-source project.  If you implement something and wish to submit it for review (via a PR) we would certainly consider adding it.  We encourage additions/improvements from the broader community! 

Bill R.
MAQS Product Owner
