### ISSUE TITLE
The content of the response from PostWithResponse is not accurate

### ISSUE THREAD

**Issue by pjotal** [Magenic/MAQS#387]
i tried to use the WebServiceDriver today and noticed that the `response.Content` when i make a request using `PostWithResponse` is not correct. instead of the response body, it gives me what i sent in the request body. below is a code snippet so you can reproduce in your end.

NOTE: jsonplaceholder is a virtual service available publicly. the response is a mock but is consistent.

```
/*
the request:
POST https://jsonplaceholder.typicode.com/posts
{
   "userId": 5,
   "id": 1,
   "title": "hello",
   "body": "world"
}

the expected response:
{
  "id": 101
}
*/

[Test]
public void POSTPost()
{
   var newPost = new Post(5, 1, "my title", "my description");
   var content = WebServiceUtils.MakeStringContent<Post>(newPost, Encoding.UTF8, contentTypeJson);

   var response = this.WebServiceDriver.PostWithResponse("/posts", contentTypeJson, content);
   Assert.AreEqual(response.StatusCode, HttpStatusCode.Created);
   Task<string> body = response.Content.ReadAsStringAsync();
   var sBody = body.Result;
   Assert.AreEqual(sBody, "{ \"id\": 101 }");
}
```

**Comment by FermJacob** [comment]
Hi @pjotal 

The example provided on typicode.com shows the following json result:
![image](https://user-images.githubusercontent.com/11142854/84583892-fcd0ed00-adc3-11ea-9da7-2d7e634d796e.png)

Looks like the output format of 
``` json
{
  "userId": 5,
  "id": 101,
  "title": "My Title",
  "body": "My Description"
}
```
is expected with the ID incremented to 101.

**Comment by TroyWalshProf** [comment]
@pjotal can you confirm that the expected response should only return the ID?

As @FermJacob mentioned, their code on [GitHub](https://github.com/typicode/jsonplaceholder) shows that you will get the more verbose response.
Also tried using Postman and got the same result.

**Note*** 
We strongly discourage doing this:
`
  Assert.AreEqual(sBody, "{ \"id\": 101 }");
`
Strict string matches can be very fragile, we generally recommend using the built in deserialization instead. 
Here is what I mean:
You can get the body and deserialize it using the web service utils:
https://magenic.github.io/MAQS/#/MAQS_5/WebService/WebServiceUtilities?id=deserializejson
Better than that you can pass in the expected response type and just have MAQS deserialize the body for you: 
https://github.com/Magenic/MAQS/blob/20e7051fa85d4afdc2924051de14569a491f0d75/Framework/WebServiceUnitTests/WebServiceStatusCodes.cs#L71

**Comment by pjotal** [comment]
@TroyWalshProf i don't know what happened here to make me get that first response. i tried to reproduce again today and i got the same response that @FermJacob described. so it's working properly.

don't worry about the string comparison on the Assert, i just did that to save time. if it was a real test i would do an object comparison instead, not string :)
depending on the json framework you use the params can come in a different order, different formatting and etc. string comparisons would be a shoot in the foot. thanks for being kind and take the time to point that out and advocating on best practice. much appreciated.
