### ISSUE TITLE
TaskCanceledException when using PostWithResponse

### ISSUE THREAD

**Issue by pjotal** [Magenic/MAQS#390]
hi,

this was supposed to be an update on #387 but as it's now closed i decided to report as a new ticket.

after modifying the test to follow the best practices i noticed the following error and it's pretty consistent. from what i googled, when consuming a `HttpResponseMessage` i should get the response using `ReadAsStringAsync()` or `ReadAsStreamAsync()` otherwise i can get this `TaskCanceledException`.

the exception
```
System.Threading.Tasks.TaskCanceledException : The operation was canceled.
  ----> System.IO.IOException : Unable to read data from the transport connection: Operation canceled.
  ----> System.Net.Sockets.SocketException : Operation canceled
```

here is the reworked test
```
        const string contentTypeJson = "application/json";

        [Test]
        public void CreateNewPost()
        {
            // Arrange
            var newPost = new Post("my title", "my description", 5); // this is a simple POJO, nothing special
            var content = WebServiceUtils.MakeStringContent<Post>(newPost, Encoding.UTF8, contentTypeJson);

            // Action
            var response = this.WebServiceDriver.PostWithResponse("/posts", contentTypeJson, content);

            // Assert
            Assert.AreEqual(response.StatusCode, HttpStatusCode.Created);

            // if i use this it always work
            //Task<string> body = response.Content.ReadAsStringAsync();
            //var sBody = body.Result;

            Post responsePost = WebServiceUtils.DeserializeJson<Post>(response);
            // shortcut so i don't need to implement object comparison
            Assert.AreEqual(newPost.title, responsePost.title);
            Assert.AreEqual(newPost.body, responsePost.body);
            Assert.AreEqual(newPost.userId, responsePost.userId);
            Assert.AreEqual(newPost.id, 101);
        }
```

**Comment by TroyWalshProf** [comment]
What line is this failing on?

**Comment by pjotal** [comment]
it is failing on line 44 which is this one
```
var response = this.WebServiceDriver.PostWithResponse("/posts", contentTypeJson, content);
```

below is the full stack trace.
```
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Magenic.Maqs.BaseWebServiceTest.WebServiceDriver.PostContent(String requestUri, String responseMediaType, HttpContent content, HttpStatusCode expectedStatus)
   at Magenic.Maqs.BaseWebServiceTest.WebServiceDriver.PostWithResponse(String requestUri, String expectedMediaType, HttpContent content, HttpStatusCode expectedStatus)
   at Tests.APITests.POSTPost() in /Users/myuser/Projects/MAQSSeleniumDotnetCore/SeleniumTests1/Tests/APITests.cs:line 44
--IOException
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
--SocketException
```

**Comment by TroyWalshProf** [comment]
Mind making sure there is a slash at the end of your WebServiceUri config value like this:
`"WebServiceUri": "https://SITE/demo/",`
and remove the slash from your post call like this:
`var response = this.WebServiceDriver.PostWithResponse("posts", contentTypeJson, content);`

**Comment by TroyWalshProf** [comment]
I think I know what is going on here.
You likely have something like 
`"WebServiceUri": "https://URL.com/typicode/demo/",`
for your base web service url.

The thing is that your web service url is wrong (at least according to someone at Microsoft).
This is because the underlying tool which MAQS uses for web service testing is the MS Web Api Client and it kind of expects specific things for your base url.
See: https://stackoverflow.com/questions/23438416/why-is-httpclient-baseaddress-not-working

What we would expect to see in your config is: 
`"WebServiceUri": "https://URL.com",`
and than your post should look like this
`var response = this.WebServiceDriver.PostWithResponse("typicode/demo/posts", contentTypeJson, content);`

I will see if this is something we can improve in MAQS 6, but to a certain extent we are married to the Web Api Client for now.

**Comment by TroyWalshProf** [comment]
@pjotal if this is not an effective workaround please let me know so I can get one of my Mac folks to take a look.

**Comment by pjotal** [comment]
hi @TroyWalshProf , i figured out what the issue is about.

**resolution**
the service response was often not getting back within the timeout period and this was triggering that exception. i increased the timeout just for fun and noticed that it started to pass consistently. what is sad is that that exception doesn't give us any clue of where the issue is potentially coming from. to improve that, maybe do a try-catch for that exception and check if the timeout period is reached. if so, raise a timeoutexception (or however you want to call it). otherwise, throw the original exception again. this way the developer will at least get a hint of what could be originating the issue as the exception itself it not very clear.

**about your suggestions**
i also took the chance to try your sugggestion of adding an ending slash in the `WebServiceUri` or removing the slash from the beginning of the endpoint and those didn't make any difference. so i guess it's safe to assume the system URI class is doing its job properly when it concatenates the parts. i haven't tried to put a wrong base url as mine was correct.

btw.. thanks for being proactive and commenting on possible mistakes people do, it was not my case again but i know a lot of people can fall into those mistakes due to a lack of understanding on how an API works and the pieces that composes it. kudos for taking the opportunity to cover those and show the people how to do it right :)

**a question for you**
once i realized what the issue was the next thing i tried was to use the [Repeat(30)] feature from NUnit to see how often the service would time out in 30 tries. as soon as i use the repeat, another exception is risen (see the stack trace below).

let me know if you prefer to cover this in another ticket so we don't change topics in the middle of a ticket.

error:
```
System.InvalidCastException : Unable to cast object of type 'Magenic.Maqs.BaseTest.BaseTestObject' to type 'Magenic.Maqs.BaseWebServiceTest.WebServiceTestObject'.
```

stacktrace:
```
   at Magenic.Maqs.BaseTest.BaseExtendableTest`1.get_TestObject()
   at Magenic.Maqs.BaseWebServiceTest.BaseWebServiceTest.get_WebServiceDriver()
   at Tests.APITests.POSTPost() in /Users/myuser/Projects/MAQSSeleniumDotnetCore/SeleniumTests1/Tests/APITests.cs:line 44
```

line 44: `var response = this.WebServiceDriver.Post<Post>("/posts", contentTypeJson, content, HttpStatusCode.Created);`

**Comment by TroyWalshProf** [comment]
Darn, I thought timeout was too simple. 
Funny thing is that we (@FermJacob and I) had kind of heated discussions about how to log timeouts and finally came up with: #31 

So MAQS should be thread safe but we need to do some Magic to make it thread safe for both MSTest and NUnit. 
I will split that off into it's own bug so we can track it more cleanly.
*BTW - This is part of the reason we are hesitant to add new lower level frameworks like XUnit

**Comment by pjotal** [comment]
LOL

let me know when you have a ticket to make it thread safe so we can track from there.
feel free to link it to this one.

thanks again for your support. it was much appreciated.
