### ISSUE TITLE
Help to connect TestRail

### ISSUE THREAD

**Issue by pulversss** [Magenic/MAQS#4]
I have a situation when I need to connect the integration with TestRail. But I did not find in the open spaces instructions how to do this with examples other than official documentation, but I could not figure out how to do it. I would be very grateful if someone would tell if someone has experience with this integration.

Thanks,
Maksim

**Comment by TroyWalshProf** [comment]
This is more of a TestRails question.
That being said, let me give it a shot.

Most tools like TestRail have an API you can use to programmatically upload test results. 
Indeed TestRail has one:
https://discuss.gurock.com/t/how-do-you-integrate-automation-with-testrail-test-runs/1472

The trick is that you need call the API as part of your test cleanup:
https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.testcleanupattribute.aspx
