### ISSUE TITLE
Make SoftAssert.AreEqual work with all primitive object comparison and object-object comparisons

### ISSUE THREAD

**Issue by JeffreyZacher** [Magenic/MAQS#423]
mstest and Nunit's AreEqual method can compare all primitive types and doing object-object comparison. Our SoftAssert library should have the same abilities.

Deprecate all assertion methods in SoftAssert besides .Assert(Func<>) in 6.0.  Remove completely in 7.0

**Comment by FermJacob** [comment]
@billros 

We will deprecate all functions that are not the Func<> in 6.0 and will remove the functionality in 7.x
