### ISSUE TITLE
Error when updating Magenic.Open.Maqs NuGet package from 4.0.4 to 5.0.0

### ISSUE THREAD

**Issue by marknoble** [Magenic/MAQS#5]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.Extensions.Configuration 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

Tried clearing the NuGet cache in VS 2017 but that didn't help.

**Comment by TroyWalshProf** [comment]
Unfortunately, there is no clean upgrade path from V4 to V5.
The team has made several big changes, such as moving to .Net Standard 2.0, lazy initialization of the web driver, support for multiple web drivers in a single test, slitting of the config file sections and adding support for .Net Core  to name just a few.

So there are 2 ways to upgrade

**The hard way:**

1.	Make sure you are using VS2017 or above
https://marketplace.visualstudio.com/items?itemName=NuGetTeam.NuGetPackageManagerforVisualStudio2015#review-details   
2.	Update your projects to 4.61 or above - https://docs.microsoft.com/en-us/dotnet/standard/net-standard
![image](https://user-images.githubusercontent.com/2066107/43145262-99f7ad78-8f24-11e8-8b5c-a3257c9dc8d9.png)
3.	Update your using statments
using Magenic.MaqsFramework to using Magenic.Maqs
4.	Use the system under test configurations
Config.GetValue("WebSiteBase") to SeleniumConfig.GetWebSiteBase()
5.	Remove any project references to Microsoft.VisualStudio.QualityTools.UnitTestFramework
![image](https://user-images.githubusercontent.com/2066107/43145297-b444f2bc-8f24-11e8-9f3c-74fe57cc702f.png)
6.	Use nuget to add the MSTest.TestAdapter package
7.	Update your app.config so it has a Selenium specific section
8.	Set the App.config to copy always
![image](https://user-images.githubusercontent.com/2066107/43145314-bb515fc8-8f24-11e8-9185-83ac891be5fd.png)


**The easy way:**
1.	Install the latest MAQS templates. - https://marketplace.visualstudio.com/items?itemName=vs-publisher-1465771.MAQSOpenFramework
2.	Create a new project
![image](https://user-images.githubusercontent.com/2066107/43145349-cd170028-8f24-11e8-9424-2cf7e1cc516f.png)
3.	Copy your code into the new project
Note* You will need to update your using statements and any place you use the config settings

**Comment by TroyWalshProf** [comment]
Latest version fixes some of the reference issues but I think that is as far as we are going to go in fixing this issue.
