### ISSUE TITLE
Pre-defined soft-asserts

### ISSUE THREAD

**Issue by FermJacob** [Magenic/MAQS#51]
We should allow tests to "pre-register" the SoftAsserts they intend to check. 
If, upon completion, they have not issued a SoftAssert for one of the pre-registered asserts, the test result should be changed to "Inconclusive". 

Background: if a test exits pre-maturely (coding logic error), without there being a failed assertion (soft, or otherwise), the test would blindly PASS, hiding an issue.

**Comment by skalpin** [comment]
@FermJacob How do you feel about attributes? for example

```cs
[TestMethod]
[SoftAssertNamedAsserts("one","two","three")
public void AllAssertsShouldBeCalled()
{
    var sa = new SoftAssert(this.fileLogger);
    sa.Assert(() => Assert.Pass(), "one");
    sa.Assert(() => Assert.Pass(), "two");

    if(false)
        sa.Assert(() => Assert.Pass(), "three");

    sa.FailTestIfAssertFailed();
```

would fail because named assert "three" was never called.

**Comment by TroyWalshProf** [comment]
Don't tell @billros  or  @magenicgrizzaffi, they have been asking of this for years. 
You give them this and they will start getting spoiled.

**Comment by JoshWencl** [comment]
@skalpin I'd vote on this being implicit instead of explicit.

Can we get all called methods for a test and use reflection grab all asserts and check if they were asserted on?

**Comment by TroyWalshProf** [comment]
@JoshWencl - Isn't the soft assert already implicit.  Your soft assert is part of your test object so it follows you the entire life cycle of the tests.  I think this change would ALSO allow you to be explicit.

**Comment by JeffreyZacher** [comment]
@JoshWencl @TroyWalshProf What if we are looping over entries on a table. We couldn't know at the beginning of a test how many soft asserts are actually expected to be ran.

**Comment by JoshWencl** [comment]
@TroyWalshProf " if a test exits pre-maturely (coding logic error)"

It doesn't implicitly do this.
