### ISSUE TITLE
Improve HTML Logger

### ISSUE THREAD

**Issue by FermJacob** [Magenic/MAQS#59]
@billros to provide business acceptance criteria

**Comment by billros** [comment]
I would like to see the HTML logs become more dynamic.  Issue #73 requests step and action level logging.  This request is to allow the reader of an HTML log file to choose the level of messages to display in the browser, based on the logging level.  

Given our logging levels (with ACTION and STEP added):
    <add key="LogLevel" value="VERBOSE"/>
    <add key="LogLevel" value="INFORMATION"/>
    <add key="LogLevel" value="ACTION"/>
    <add key="LogLevel" value="STEP"/>
    <add key="LogLevel" value="GENERIC"/>
    <add key="LogLevel" value="SUCCESS"/>
    <add key="LogLevel" value="WARNING"/>
    <add key="LogLevel" value="ERROR"/>-->

If Logging was done at the INFORMATION or even DEBUG level, the user could select to see ACTION through ERROR level messages and the rest of the messages would be filtered out...
