### ISSUE TITLE
Rename MAQS to reflect new company

### ISSUE THREAD

**Issue by skalpin** [Magenic/MAQS#604]
MAQS is now owned by Cognizant Softvision and needs to be renamed

**Comment by JoshWencl** [comment]
This was fast.

I vote to defer this.

**Comment by TroyWalshProf** [comment]
Update:
The name MAQS will remain.
The acronym will however change to:
Modular Automation Quick Start 
*We will also be updating the namespace to reflect the Magenic -> Softvision change
