### ISSUE TITLE
Add dropdown support for LazyElements

### ISSUE THREAD

**Issue by JeffreyZacher** [Magenic/MAQS#62]
We have element handlers for the following methods:

SelectDropDownOption
SelectDropDownOptionByValue
GetSelectedOptionFromDropdown
GetSelectedOptionsFromDropdown

it would be nice if we could call these methods on a Lazy Element because the Select methods require a By currently.

This would also add the Lazy Element logging on these controls.

**Comment by FermJacob** [comment]
Will be included in MAQS 5.7
