### ISSUE TITLE
Code Coverage: DatabaseTestObject.cs

### ISSUE THREAD

**Issue by FermJacob** [Magenic/MAQS#694]
The DatabaseTestObject.cs has a code coverage of 52.6%.  Try to increase the coverage to 100%

https://sonarcloud.io/component_measures?id=MAQS&metric=coverage&selected=MAQS%3AFramework%2FBaseDatabaseTest%2FDatabaseTestObject.cs&view=list

4

**Comment by jonreding2010** [comment]
closing issue due to DatabaseTestObject.cs is at 100% coverage
https://sonarcloud.io/component_measures?id=MAQS&metric=coverage&selected=MAQS%3ABaseDatabaseTest%2FDatabaseTestObject.cs&view=list
