### ISSUE TITLE
Add Step and/or Action Logging Level in LazyElement

### ISSUE THREAD

**Issue by billros** [Magenic/MAQS#73]
The goal of this issue is to provide a level of logging that can be used to re-create the manual steps one would take to reproduce an automated test, manually.
The first is to add a logging level called "STEP".  This would be used by the test case developer to denote a step in the user's scenario.

The second is an ACTION that is taken, on behalf of the user.  For UI tests, this would take the form of changing some of the "Information" log messages from LazyElements into "Action" messages.  Any action that is directly related to a user input (Sendkeys, click, Hover, etc) should be logged as an ACTION (currently as "INFORMATION")

Our log levels go from "GENERIC", which means success or failure of soft-asserts, to "Information" which (for selenium tests) includes every find-an-element attempt, isVisible, "going to click" and click event.  This is a bit TOO detailed.  So we would insert them in the following order (more to less detailed order):
VERBOSE
INFORMATION
ACTION
STEP
GENERIC

For web services, this would be the Sending [GET|POST|...] Log messages.

In all cases, wording should be changed to directive voice: "Click" (rather than "Clicking"), "Send" (rather than "sending"). 

In the "feature/RoskeBill-StepLoggingExample" Branch, in the MAQS/HTMLLogSpec/HTMLLogSpec/Tests/ folder,
I have annotated 2 HTML log files for For Selenium and WebService Tests.
The Orange lines that include "INTENT" are log messages from the test (These might be "step" logs messages from the test)
The Gold lines that follow are the appropriate log messages that should be "ACTION" messages.

**Comment by JeffreyZacher** [comment]
@billros For Lazy element action that are Getting (e.g. GetValue, GetSelectedOptionFromDropdown, GetAttribute, etc.) should their messages remain INFORMATION?

**Comment by billros** [comment]
Yes

**Comment by JeffreyZacher** [comment]
@TroyWalshProf @FermJacob can we close this?

**Comment by TroyWalshProf** [comment]
Covered in #162
