### ISSUE TITLE
Support 2022 Visual Studio

### ISSUE THREAD

**Issue by pulversss** [Magenic/MAQS#856]
Hello.
 I installed the latest studio for myself, but I cannot find your system in the market for this studio. Will there be support? or need to downgrade to the previous version of the studio?

Thanks 
Maksim.

**Comment by TroyWalshProf** [comment]
As Studio is still in preview we haven't bothered to update these templates yet.
That being said we will be looking at this very soon

Also note there is an alternative.
You can use the Dotnet cli to create a MAQS project and then just use Studio 2022 for development.
See: https://youtu.be/Wtm_ttP6KSo?t=209

**Comment by TroyWalshProf** [comment]
Added an issue in our templates project - https://github.com/Magenic/MAQS-Extensions/issues/347

**Comment by TroyWalshProf** [comment]
Fixed with https://github.com/Magenic/MAQS-Extensions/pull/348
