### ISSUE TITLE
Error message is displayed

### ISSUE THREAD

**Issue by pulversss** [Magenic/MAQS#9]
---------------------------
Microsoft Visual Studio
---------------------------
A problem was encountered creating the sub project 'PageModel'.  Unable to copy the file 'BasePageModel.cs' from the project template to the project. Cannot find file "C:\Users\User\AppData\Local\Temp\iqjtamzv.3vy\Temp\BasePageModel.cs".
---------------------------
OK   
---------------------------

Where I create a new project.  Please Help me!

**Comment by TroyWalshProf** [comment]
Will have a fix out by the end of day.
Thank you for bringing this to our attention.

**Comment by TroyWalshProf** [comment]
The Visual Studio extension has fixed, tested and released.
You can update the extension in Visual Studio or download the updated extension from:
https://marketplace.visualstudio.com/items?itemName=vs-publisher-1465771.MAQSOpenFramework
