### ISSUE TITLE
How to GetDevToolsSession() in MAQS 7

### ISSUE THREAD

**Issue by pjotal** [Magenic/MAQS#910]
The documentation so far doesn't describe how we can leverage one of the richest features of Selenium 4 in MAQS 7, which is using Chrome dev tools.

I tried the following piece of code and got an error.
`DevToolsSession session = ((ChromeDriver)WebDriver).GetDevToolsSession();`

error: `System.InvalidCastException : Unable to cast object of type 'OpenQA.Selenium.Support.Events.EventFiringWebDriver' to type 'OpenQA.Selenium.Chrome.ChromeDriver'.`

Haven't anything in the documentation describing classes to support the usage of Selenium Bidi or CDP so would like to suggest you document how we can use CDP until an official implementation is provided via MAQS.

thanks :)

**Comment by TroyWalshProf** [comment]
DevToolsSession session = ((ChromeDriver)WebDriver.**_GetLowLevelDriver()_**).GetDevToolsSession();

**Comment by pjotal** [comment]
hi troy,

It seems `GetLowLevelDriver()` is not available at the test class level.

Got it going with the following code but i am not sure this is what you would suggest.
```
var driver = WebDriverFactory.GetDefaultBrowser();
TestObject.WebManager.OverrideDriver(driver);
var session = ((ChromeDriver)driver).GetDevToolsSession();
```

**Comment by TroyWalshProf** [comment]
Add the following using statement to be able to access GetLowLevelDriver:
Using Magenic.Maqs.BaseSeleniumTest.Extensions

**Comment by pjotal** [comment]
worked for me. thanks :)
feel free to close the ticket if you wish.

btw.. any chances you'll include some new features to easy intercepting request and response calls in near future releases? that would be great.

**Comment by TroyWalshProf** [comment]
This can be done with the Playwright feature in MAQS 9
Note* The MAQS project has moved to here:
https://github.com/CognizantOpenSource/maqs-dotnet
